### ISSUE TITLE
Failed to load graph data: Request did not reach the server. (Server offline / Adblocker?)

### ISSUE THREAD

**Issue by Leonardo-Fiori** [plan-player-analytics/Plan#1490]
Lately i always get this error message when i look at graphs:
"Failed to load graph data: Request did not reach the server. (Server offline / Adblocker?)"

Other statistics work fine. The plugin in general seems good. But i can't load graphs on chrome. I don't use any adblocker, and of course my server is online.

### Server information
git-Paper-347 (MC: 1.15.2)
Plan version 5.1 build 600

### Exceptions & Other Logs
https://hastebin.com/vesegozese.css

**Comment by Rsl1122** [comment]
There isn't enough information for me to figure out what the issue is, could you send enable log of Plan from the console?

**Comment by Leonardo-Fiori** [comment]
Which is the command to enable logging? Can't find it anywhere

**Comment by Leonardo-Fiori** [comment]
This is plan's startup anyway:

`[12:23:44 INFO]: [Plan] Enabling Plan v5.1 build 600
[12:23:44 INFO]:
[12:23:44 INFO]:            ██▌
[12:23:44 INFO]:      ██▌   ██▌
[12:23:44 INFO]:   ██▌██▌██▌██▌  Player Analytics
[12:23:44 INFO]:   ██▌██▌██▌██▌  v5.1 build 600
[12:23:44 INFO]:
[12:23:44 INFO]: [Plan] Locale: 'English' by Rsl1122
[12:23:44 INFO]: [Plan] SQLite-database connection established.
[12:23:44 INFO]: WebServer: Proxy-mode HTTPS enabled, make sure that your reverse-proxy is routing using HTTPS and Plan Alternative_IP.Link points to the Proxy
[12:23:44 INFO]: [Plan] Webserver running on PORT 8804 (https://plan.peacefulvanilla.club:8804)
[12:23:44 INFO]: [Plan] Registered extension: AdvancedAntiCheat
[12:23:44 INFO]: [Plan] Registered extension: Essentials
[12:23:44 INFO]: [Plan] Registered extension: LuckPerms
[12:23:44 INFO]: [Plan] Registered extension: nuVotifier
[12:23:44 INFO]: [Plan] Registered extension: SuperbVote
[12:23:44 INFO]: [Plan] Registered extension: Economy (Vault)
[12:23:44 INFO]: [Plan] Registered extension: Permission Groups (Vault)
[12:23:44 INFO]: [Plan] Registered extension: ViaVersion
[12:23:44 INFO]: [Plan] Player Analytics Enabled. (266 ms)
`

**Comment by Rsl1122** [comment]
From the proxy mode I assume you're running Plan behind a proxy.

Could the proxy be limiting the size of the response for the graphs? I know that in the past some people had issues with nginx maximum response size being too small for the response Plan is sending, but I can't for some reason find the specific setting that affects it right now

**Comment by Leonardo-Fiori** [comment]
I am under ddos protection service called TCPShield. Maybe I should contact the guy that manages it?

**Comment by Leonardo-Fiori** [comment]
@Rsl1122 nope!

I tried again, this time connecting via the clear IP:PORT, so no proxy.

Failed to load graph data: Timed out after 45 seconds. (../v1/graph?type=performance&server=26485b43-c788-4711-a6ab-c6383d1d6e0c)

Looks like there is something wrong with plan itself... it takes ages to load, sometimes now it works, but 90% of the times it spits out that error. So i guess that my anti ddos protection is only closing the connection before that message appears.

**Comment by Rsl1122** [comment]
Sounds like the database is not replying fast enough to the response. You can try reducing the timed data removal threshold in the Plan config under `Time.Thresholds` to reduce the amount of data.

**Comment by Leonardo-Fiori** [comment]
Configured it like this:
```
    Thresholds:
        # How long player needs to be idle until Plan considers them AFK
        AFK_threshold: 2
            Unit: MINUTES
        # Activity Index considers last 3 weeks and uses these thresholds in the calculation
        # The index is a number from 0 to 5.
        # These numbers were calibrated with data of 250 players (Small sample size).
        Activity_index:
            Playtime_threshold: 30
                Unit: MINUTES
        Remove_inactive_player_data_after: 90
            Unit: DAYS
        # Includes players online, tps and performance time series
        Remove_time_series_data_after: 90
            Unit: DAYS
        Remove_ping_data_after: 14
            Unit: DAYS
        Remove_disabled_extension_data_after: 2
            Unit: DAYS
    Periodic_tasks:
        Extension_data_refresh_every: 1
            Unit: HOURS
        Check_DB_for_server_config_files_every: 1
            Unit: MINUTES
        Clean_Database_every: 15
            Unit: MINUTES
```

Reloaded plan but the problem still persists

**Comment by Rsl1122** [comment]
Dunno then. 
You could try export to have something always available (see wiki external webserver use).
You might need to wait for #1459 to have this problem resolved with the Plan webserver.

**Comment by Leonardo-Fiori** [comment]
Problem is still happening, as last time i am not under any kind of anti ddos or proxy. Connecting straight to my ip. I get this error and graph won't load 90% of the times:

Failed to load graph data: Timed out after 45 seconds

Just updated plan to latest build ( Plan version 5.1 build 624 )

And Paper version git-Paper-131 (MC: 1.16.1)

**Comment by Rsl1122** [comment]
- You could try export and another webserver <https://github.com/plan-player-analytics/Plan/wiki/External-WebServer-Use>
- You might need to wait for #1459 to have this problem resolved when using the Plan webserver.

**Comment by Leonardo-Fiori** [comment]
Ill'wait for sure, i am 100% noob with webservers on linux! Is there an ETA for that feature?

**Comment by Rsl1122** [comment]
Unfortunately no ETA - I'll probably be able to continue normal speed development after August when my job contract ends, right now it is going at a snail pace.

**Comment by Leonardo-Fiori** [comment]
Understandable! Doing an amazing job so far! I will wait
