### ISSUE TITLE
Viaversion extension giving an error.

### ISSUE THREAD

**Issue by MikkelHebel** [plan-player-analytics/Plan#2989]
### Describe the issue
This became an issue when I updated the plugin on my bungeecord proxy server from version 2172 to 2307.
The console report the following string: "Report and/or disable ViaVersion extension in the Plan config."

### Exceptions & Other Logs

[DataExtensionMethodCallException-b1a2ac6f8d.txt](https://github.com/plan-player-analytics/Plan/files/11325774/DataExtensionMethodCallException-b1a2ac6f8d.txt)

```
Registered extension: ViaVersion
Player Analytics Enabled.
Enabled plugin Plan version 5.5 build 2307 by AuroraLS3
Enabled plugin cmd_list version git:cmd_list:1.19-R0.1-SNAPSHOT:b19e570:514 by WaterfallMC
[Mod Checker]: Enabled
Enabled plugin HackedServer version 2.84.1 by Th0rgal
Enabled plugin Geyser-BungeeCord version 2.1.0-SNAPSHOT by GeyserMC
******************************************
[Geyser-BungeeCord]:
Loading Geyser version 2.1.0-SNAPSHOT (git-master-0f99abc)
[Geyser-BungeeCord]:
******************************************
Enabled plugin ACNotify version Build 7 by HKNGLGN
Enabled plugin cmd_find version git:cmd_find:1.19-R0.1-SNAPSHOT:b19e570:514 by WaterfallMC
Enabled plugin cmd_server version git:cmd_server:1.19-R0.1-SNAPSHOT:b19e570:514 by WaterfallMC
Validating your server key...
All database patches applied successfully.
Enabled plugin BuycraftX version 12.0.8 by Buycraft
Enabled plugin cmd_alert version git:cmd_alert:1.19-R0.1-SNAPSHOT:b19e570:514 by WaterfallMC
20.38.15
Enabled plugin floodgate version 2.2.2-SNAPSHOT (b??-2702bc3) by GeyserMC
Enabled plugin cmd_send version git:cmd_send:1.19-R0.1-SNAPSHOT:b19e570:514 by WaterfallMC
Enabled plugin ViaBackwards version 4.6.1 by Matsv, kennytv, Gerrygames, creeper123123321, ForceUpdate1
Listening on /194.163.149.210:25565
Fetching all due players...
20.38.16
Fetched due players (0 found).
20.38.20
Started Geyser on 0.0.0.0:25565
Done (5.998s)! Run /geyser help for help!
20.38.25
Access Log: GET /network (from X.X.X.X) - 304
Access Log: GET /static/js/main.f323be30.js (from X.X.X.X) - 304
Access Log: GET /static/css/main.7a30e409.css (from X.X.X.X) - 304
Access Log: GET /pageExtensionApi.js (from X.X.X.X) - 200
Access Log: GET /favicon.ico (from X.X.X.X) - 200
20.38.36
Access Log: GET /network (from X.X.X.X) - 304
Access Log: GET /static/js/main.f323be30.js (from X.X.X.X) - 304
Access Log: GET /static/css/main.7a30e409.css (from X.X.X.X) - 304
Access Log: GET /pageExtensionApi.js (from X.X.X.X) - 200
20.38.40
Access Log: GET /network (from X.X.X.X) - 304
Access Log: GET /static/js/main.f323be30.js (from X.X.X.X) - 304
Access Log: GET /static/css/main.7a30e409.css (from X.X.X.X) - 304
Access Log: GET /pageExtensionApi.js (from X.X.X.X) - 200
20.38.41
Access Log: GET /favicon.ico (from X.X.X.X) - 200
WARN20.38.43
Ran into DataExtensionMethodCallException - logged to plugins/Plan/logs/DataExtensionMethodCallException-b1a2ac6f8d.txt
(INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
What to do: Report and/or disable ViaVersion extension in the Plan config.
```

### Plugin versions
Plan v5.5 build 2307

### Additional information
I'm not sure if this is due to this issue but I can't use the web panel any more. This happened when the this issue started.

**Comment by Scot-Survivor** [comment]
Can confirm I am getting a similar bug, after I moved to Velocity also

**Comment by AuroraLS3** [comment]
The error in the error log is fixed in dev build https://github.com/plan-player-analytics/Plan/releases/tag/5.5.2335 (It automatically corrects the bad char encoding)

The exception is unrelated to not being able to access the web panel - you may need to clear browser cache.

**Comment by MikkelHebel** [comment]
I have cleared my browser cache and also tried using another browser and it did not resolve the issue. Even after I updated to the dev version.

**Comment by AuroraLS3** [comment]
Is there anything on the browser console when you try to open the page? (Ctrl + Shift + I, Console on the browser)

**Comment by MikkelHebel** [comment]
cess to XMLHttpRequest at 'http://stats.mydomain.com/v1/locale' from origin 'http://stats.mydomain.com:8804' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
main.0ceb2ff0.js:2 D
(anonymous) @ main.0ceb2ff0.js:2
/v1/locale:1     Failed to load resource: net::ERR_FAILED
main.0ceb2ff0.js:2 react-i18next:: i18n.languages were undefined or empty Array(0)
r @ main.0ceb2ff0.js:2
network#tab-network-overview&online-tab:1 Access to XMLHttpRequest at 'http://stats.mydomain.com/v1/metadata' from origin 'http://stats.mydomain.com:8804' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
main.0ceb2ff0.js:2 D
(anonymous) @ main.0ceb2ff0.js:2
/v1/metadata:1     Failed to load resource: net::ERR_FAILED
network#tab-network-overview&online-tab:1 Access to XMLHttpRequest at 'http://stats.mydomain.com/v1/whoami' from origin 'http://stats.mydomain.com:8804' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
main.0ceb2ff0.js:2 D
(anonymous) @ main.0ceb2ff0.js:2
/v1/whoami:1     Failed to load resource: net::ERR_FAILED
DevTools failed to load source map: Could not load content for chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for http://stats.mydomain.com:8804/static/js/2445.7644283a.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://stats.mydomain.com:8804/static/js/9603.84ba3daf.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://stats.mydomain.com:8804/static/js/4956.3c42436f.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://stats.mydomain.com:8804/static/js/main.0ceb2ff0.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://stats.mydomain.com:8804/static/js/8023.e946b5a4.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://stats.mydomain.com:8804/static/js/611.dfdaea63.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://stats.mydomain.com:8804/static/js/460.348ad76d.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://stats.mydomain.com:8804/static/css/main.88bade62.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by AuroraLS3** [comment]
Try put `stats.mydomain.com:%port%` or `stats.mydomain.com` to `Webserver.Alternative_IP.Address` in Plan config

**Comment by MikkelHebel** [comment]
For some reason putting %port% behind it worked. Thank you. Just think it's weird since it worked before the update.
