### ISSUE TITLE
Very high memory

### ISSUE THREAD

**Issue by JHarris12345** [plan-player-analytics/Plan#3838]
### Describe the issue

The memory usage is VERY high in the MySQL transaction thread. Here are some screenshots:
https://gyazo.com/13c72192a83797fead323e893a3ce195
https://gyazo.com/8d4f47fd75a2034ce5f3086d3739bcba

### Exceptions & Other Logs

```

```

### Plugin versions

Plan-5.6-build-2614.jar

**Comment by AuroraLS3** [comment]
You are using a version that is over 200 commits behind. This bug has been fixed, please update the plugin.

**Comment by AuroraLS3** [comment]
@404forever1 Folia may behave differently with memory, I'd need a heap dump or at least screenshots from Eclipse Memory Analyzer to confirm what is using the memory.

**Comment by JHarris12345** [comment]
> You are using a version that is over 200 commits behind. This bug has been fixed, please update the plugin.

Hi, this bug is not fixed. I updated to the latest and plan is still showing INSANE usage https://gyazo.com/ffbeac594992820a2c6826f4d48b123e

**Comment by AuroraLS3** [comment]
StackTraceElement suggests errors being thrown.

7.3M entries of #5 come from other plugins using Plan API (QuerySvc), #10, 11 & 12 are the supporting functions for those calls.

I suggest disabling all plugins under Plan config Plugins section to see if that helps.

Also where is this picture from? Did it perform GC (Garbage Collection) before snapshot? (Java uses whatever memory it is allocated, so without GC you won't know actual memory usage)

**Comment by JHarris12345** [comment]
This image is a spark heap summary

**Comment by JHarris12345** [comment]
And look at this. 11GB of my heap (of only 14GB) is JUST plans mysql transaction thread https://gyazo.com/20cce6d06b133683d0ffe152c6cfbedc

**Comment by AuroraLS3** [comment]
I'd need to look deeper at the contents of the heap dump to say what is doing so many transactions that the database can not keep up. (Or is the database throwing errors?)

As far as I can see, continuing my previous comment, another plugin is using Plan API for it's database storage and not doing it efficiently. This is the hypothesis until I can look at what is in there.
